exclude: '(?x)^(manifests/.*/charts/.*)'
repos:
  # general stuff
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch

      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        exclude: |
          (?x)^(
              packages/backend/workflows/.*|
              charts/
          )$
        args: [--allow-multiple-documents]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.6' # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@^2.3.2
          - '@spotify/prettier-config@^12.0.0'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.37.0' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
