apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ${{ values.name }}
spec:
  components:
    - name: ${{ values.basic.name }}
      type: edgefarm-applications
      properties:
        image: ${{ values.basic.image }}
        nodepoolSelector:
          matchLabels:
            {%- set varArray = values.basic.target.split("=") %}
            ${{ varArray[0] }}: "${{ varArray[1] }}"
        name: ${{ values.basic.name }}
        {%- if values.advanced.command %}
        command:
          {%- for cmd in values.advancedCommand %}
            - ${{ cmd }}
          {%- endfor %}
        {%- endif %}
        {%- if values.advanced.args %}
        args:
          {%- for arg in values.advancedArgs %}
            - ${{ arg }}
          {%- endfor %}
        {%- endif %}
        cpu: ${{ values.advancedCpu }}
        memory: ${{ values.advancedMemory -}}
        {% if values.advancedEnvs | length > 0 %}
        env:
          {%- for env in values.advancedEnvs %}
          - name: ${{ env.name }}
            value: ${{ env.value }}
          {%- endfor %}
        {%- endif %}
        {% if values.advancedPorts | length > 0 -%}
        ports:
          {%- for mapping in values.advancedPorts %}
          - containerPort: ${{ mapping.containerPort }}
            hostPort: ${{ mapping.hostPort }}
            {% if mapping.protocol | length > 0 -%}
            protocol: ${{ mapping.protocol }}
            {%- endif %}
            {% if mapping.name | length > 0 -%}
            name: ${{ mapping.name }}
             {%- endif %}
          {%- endfor %}
        {%- endif %}
      {%- if values.enableNetwork or values.advanced.storage.hostPaths|length > 0 %}
      traits:
      {%- endif %}
        {%- if values.enableNetwork %}
        - type: edgefarm-network
          properties:
            network:
              name: ${{ values.networkSettings.network }}
              subnetwork: ${{ values.networkSettings.subnetwork }}
              user: ${{ values.networkSettings.user }}
        {%- endif %}
        {%- if values.advanced.storage.hostPaths|length > 0 %}
        - type: edgefarm-storage
          properties:
            hostPath:
            {%- for hostPath in values.advanced.storage.hostPaths %}
              - name: ${{ hostPath.name }}
            {%- endfor %}
        {%- endif %}