apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: edgefarm-application-add
  title: Add an Application
  tags:
    - edgefarm
    - application
    - deployment
    - recommended
    - kubernetes
  links:
    - title: Documentation
      url: https://edgefarm.github.io/edgefarm/
spec:
  type: service
  parameters:
    - title: General
      required:
        - name
        - system
      properties:
        system:
          title: Select your system
          description: Here you can select one of your existing systems. If you don't have any, you need to create one first.
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: system
            defaultKind: System
        name:
          title: Name your application
          type: string
          description: Unique name of the application within the system
          maxLength: 253 # DNS subdomain name rules: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
          pattern: "^[a-z0-9][a-z0-9-]*$"
          ui:autofocus: true
          ui:options:
            rows: 5

    - title: Application
      required:
        - basic
      properties:
        basic:
          type: object
          title: Basic configuration
          required:
            - name
            - image
            - target
          properties:
            name:
              type: string
              title: Name of the component, e.g. "foo"
              ui:autofocus: true
            image:
              type: string
              title: OCI image
              description: Location of the OCI image, e.g. "foo", "foo:latest", "ghcr.io/foo/bar:latest", "docker.io/foo/bar:latest"
            target:
              type: string
              title: Nodepool selector
              description: A selector that addresses target nodepools. e.g. "foo=bar", "foo="
              pattern: ^([a-z0-9][a-z0-9\-\.]{0,252}\/)?[a-z0-9A-Z][a-z0-9A-Z\-\_\.]{0,62}=([a-z0-9A-Z][a-z0-9A-Z\-\_\.]{0,62})?$
            enableAdvanced:
              title: Expand/collapse advanced configuration view
              description: Advanced configurations like command, args, cpu and memory.
              type: boolean
              default: false
              ui:widget: checkbox
          dependencies:
            enableAdvanced:
              oneOf:
                - properties:
                    enableAdvanced:
                      const: false
                - properties:
                    enableAdvanced:
                      const: true
                    advanced:
                      type: object
                      title: Advanced configuration
                      required:
                        - cpu
                        - memory
                      properties:
                        command:
                          type: string
                          title: container startup command (optional)
                          description: "If needed, define the executable to run when the container starts."
                        args:
                          type: string
                          title: Arguments for startup command (optional)
                          description: "If needed, define the args for the startup executable."
                        cpu:
                          type: string
                          title: CPU limit
                          description: "Specify the amount of cpu for requests and limits, e.g.: 0.4"
                          default: "0.25"
                        memory:
                          type: string
                          title: Memory limit
                          description: "Specify the amount of memory for requests and limits e.g.: 512Mi"
                          pattern: "^([1-9][0-9]{0,63})(Ei|Pi|Ti|Gi|Mi|Ki)$"
                          default: "256Mi"

    - title: Network
      properties:
        enableNetwork:
          title: Network used?
          description: Select if the application uses an EdgeFarm.network
          type: boolean
          default: false
          ui:widget: checkbox
      dependencies:
        enableNetwork:
          oneOf:
            - properties:
                enableNetwork:
                  const: false
            - properties:
                enableNetwork:
                  const: true
                networkSettings:
                  type: object
                  title: Configuration
                  properties:
                    network:
                      type: string
                      title: Network
                      description: "Define the network name to connect to."
                    subnetwork:
                      type: string
                      title: Sub-Network
                      description: "Define the sub-network within the network to use."
                    user:
                      type: string
                      title: User
                      description: "Define the user within your network your application uses."
                  required:
                    - network
                    - subnetwork
                    - user
  steps:
    - id: system-fetch
      name: Fetch system entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.system }}

    - id: toknizeCommand
      action: edgefarm:applications:command:tokenize
      name: Prepare application command
      input:
        inputString: ${{ parameters.basic.advanced.command }}

    - id: toknizeArgs
      action: edgefarm:applications:command:tokenize
      name: Prepare application command args
      input:
        inputString: ${{ parameters.basic.advanced.args }}

    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        targetPath: applications/${{ parameters.name }}
        values:
          clusterName: ${{ steps['system-fetch'].output.entity.metadata.annotations['edgefarm.io/cluster'] }}
          name: ${{ parameters.name }}
          basic: ${{ parameters.basic }}
          advanced: ${{ parameters.basic.advanced }}
          advancedCommand: ${{ steps['toknizeCommand'].output.tokenizedData }}
          advancedArgs: ${{ steps['toknizeArgs'].output.tokenizedData }}
          enableNetwork: ${{ parameters.enableNetwork }}
          networkSettings: ${{ parameters.networkSettings }}
          owner: ${{ user.entity.metadata.namespace }}/${{ user.entity.metadata.name }}
          system: ${{ parameters.system }}
    # - id: list-workspace
    #   name: List Workspace
    #   action: debug:log
    #   input:
    #     listWorkspace: true
    # - id: read-catalog-info
    #   name: Read generated catalog-into.yaml
    #   action: ci4rail:fs:read
    #   input:
    #     path: ./applications/${{ parameters.name }}/catalog-info.yaml
    # - id: log-catalog-info
    #   name: Log generated catalog-into.yaml
    #   action: debug:log
    #   input:
    #     message: ${{ steps['read-catalog-info'].output.content }}
    # - id: read-manifest
    #   name: Read generated manifest
    #   action: ci4rail:fs:read
    #   input:
    #     path: ./applications/${{ parameters.name }}/manifests/application.yaml
    # - id: log-manifest
    #   name: Log  generated manifest
    #   action: debug:log
    #   input:
    #     message: ${{ steps['read-manifest'].output.content }}

    - id: pull-request
      name: Persist changes on Github
      action: publish:github:pull-request
      input:
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoUrl: ${{ steps['system-fetch'].output.entity.metadata.annotations['edgefarm.io/repo'] }}
        branchName: add-application-${{ parameters.name }}-definition
        title: Add application ${{ parameters.name }} definition
        description: Adds a new application with name ${{ parameters.name }}
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.spec.profile.email }}

  output:
    links:
      - title: Verify on Github
        url: ${{ steps['pull-request'].output.remoteUrl }}
