
name: Lint Commit Messages
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
      - beta

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # workaround for https://github.com/conventional-changelog/commitlint/issues/3256
      - run: rm -f tsconfig.json
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
