name: Release

on:
  push:
    branches:
      - main

jobs:
  do-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install yarn
        run: |-
          #!/bin/bash
          set -e
          npm install --global yarn

      - name: Install dependencies
        run: |-
          #!/bin/bash
          set -e
          yarn install --non-interactive

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: yoda
        run: |-
          #!/bin/bash
          set -e
          yarn add semantic-release @semantic-release/exec @eclass/semantic-release-docker -D -W
          # the ... || true is to prevent the script from failing caused by a bug in semantic-release regarding
          # rate limit changes on github. See https://github.com/semantic-release/github/pull/487
          npx semantic-release || true
