
name: TSC Lint
on:
  pull_request:
    branches:
      - "**"

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 16.x
            - name: Run 'yarn install'
              uses: borales/actions-yarn@v4
              with:
                cmd: install # will run `yarn install` command
            - name: Run 'yarn tsc'
              uses: borales/actions-yarn@v4
              with:
                cmd: tsc # will run `yarn tsc` command
